apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: actix
  name: actix
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: actix
    spec:
      containers:
      - env:
        - name: RUST_ENV
          value: docker
        - name: RUST_LOG
          value: debug
        image: generalset/multiplayer_server:init
        name: actix
        ports:
        - containerPort: 3001
        resources: {}
      restartPolicy: Always
status: {}
