#!/usr/bin/env bash

export NODE_ENV=production

pushd client && \
    (yarn install; yarn build-prod || true) && \
    popd
pushd server && \
    (yarn install; yarn prestart || true) && \
    pm2 kill && \
    pm2 start node app.js && \
    popd
