version: '3'
services:
  actix:
    environment:
      - RUST_ENV=docker
      - RUST_LOG=debug
    build: .
    ports: 
      - '3001:3001'
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
volumes:
  redis-data: